# GitHub Actions workflow for deploying to GitHub Pages
# This is optional but ensures proper deployment

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job (not needed for static files, but good for validation)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Validate files
        run: |
          # Check if required files exist
          test -f index.html || (echo "index.html not found" && exit 1)
          test -f manifest.json || (echo "manifest.json not found" && exit 1)
          test -f service-worker.js || (echo "service-worker.js not found" && exit 1)
          test -f style.css || (echo "style.css not found" && exit 1)
          test -f script.js || (echo "script.js not found" && exit 1)
          echo "All required files found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
